name: Docker Image CI

on:
  push:
    branches: [ "main" ]
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env: 
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
       echo '{"auths": {"https://index.docker.io/v1/": {"auth": "'$(echo -n "$DOCKER_USERNAME:$DOCKER_PASSWORD" | base64 -w 0)'"}}}' > ~/docker_auth.json
       export DOCKER_CONFIG=~/docker_config
       mkdir -p $DOCKER_CONFIG
       mv ~/docker_auth.json $DOCKER_CONFIG/config.json
       docker login -u "$DOCKER_USERNAME" --config=$DOCKER_CONFIG --password-stdin


    - name: Build the Docker image
      run: docker build -t cicd-pipeline . 
    - name: Push to Dockerhub
      run: docker push prthmsh77/cicd-pipeline:latest
